### ISSUE TITLE
 java.lang.ClassNotFoundException: riemann.jvm_profiler.Agent

### ISSUE THREAD

**Issue by hkandasa** [riemann/riemann-jvm-profiler#7]
I built the profiling jar using lein as mentioned in https://github.com/riemann/riemann-jvm-profiler

Here is the command to run this as a java agent
-javaagent:'/var/opt/lib/riemann-jvm-profiler-0.1.0.jar=prefix=MyApp,host=MyRiemannServer'

At the runtime i see this error

Exception in thread "main" java.lang.ClassNotFoundException: riemann.jvm_profiler.Agent
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

My Lein Version
lein --version
Leiningen 1.7.1 on Java 1.8.0_66 Java HotSpot(TM) 64-Bit Server VM

When i unzip the riemann-jvm-profiler-0.1.0.jar,I just see stack.clj under /riemann/jvm_profiler
I see Agent.Java under /riemann
Is there any problem with the build.

**Comment by hkandasa** [comment]
Issue with lein version.. Issue was resolved after upgrading lein version
